### ISSUE TITLE
Polars usage

### ISSUE THREAD

**Issue by omarirfa** [guestrin-lab/lotus#55]
Hey!

Congrats on releasing the v1, I just saw a post on twitter (by Liana) and wanted to check it out. I do see this works alot with Pandas however, looking at the docs it seems we could potentially use this with [Polars](https://pola.rs/) as well. I just wanted to ask before I start using if that is something that we can utilize while using Lotus. Polars is also a dataframe library albeit, slightly different syntax.

**Comment by sidjha1** [comment]
Hey @omarirfa, thanks for the interest! Unfortunately we don't currently support `polars` and do not have the bandwidth to add it to our roadmap.

**Comment by glesperance** [comment]
@sidjha1 would you be open at a PR adding polars support or it that 100% out of scope?

**Comment by sidjha1** [comment]
@glesperance Very open to the idea, feel free to open a PR!
