### ISSUE TITLE
Failing mypy pre-commit hook

### ISSUE THREAD

**Issue by dhruviyer** [guestrin-lab/lotus#60]
I'm seeing a few failing checks when running the `my-py` precommit hooks on `cascade_utils.py`:

`lotus/sem_ops/cascade_utils.py:30: error: Incompatible return value type (got "tuple[ndarray[tuple[int, ...], dtype[Any]], ndarray[tuple[int, ...], dtype[floating[Any]]]]", expected "tuple[ndarray[tuple[int, ...], dtype[signedinteger[_64Bit]]], ndarray[tuple[int, ...], dtype[float64]]]")`

`lotus/sem_ops/cascade_utils.py:95: error: Argument 1 to "calculate_tau_neg" has incompatible type "list[tuple[float, bool, float64]]"; expected "list[tuple[float, bool, float]]"`

`lotus/sem_ops/cascade_utils.py:115: error: Argument 1 to "calculate_tau_neg" has incompatible type "list[tuple[float, bool, float64]]"; expected "list[tuple[float, bool, float]]"`

`lotus/sem_ops/cascade_utils.py:134: error: Argument 3 to "precision" has incompatible type "list[tuple[float, bool, float64]]"; expected "list[tuple[float, bool, float]]"`

`lotus/dtype_extensions/image.py:145: error: Incompatible types in assignment (expression has type "list[Image | str | None]", target has type "_SupportsArray[dtype[Any]] | _NestedSequence[_SupportsArray[dtype[Any]]] | bool | int | float | complex | str | bytes | _NestedSequence[bool | int | float | complex | str | bytes]")`

**Comment by sidjha1** [comment]
Hey @dhruviyer is it due to the `mypy` version? Here are my versions
```
mypy==1.13.0
mypy-extensions==1.0.0
```

**Comment by dhruviyer** [comment]
@sidjha1 looks like I have the same versions

**Comment by dhruviyer** [comment]
I'm going to close this issue because for some reason it hasn't re-emerged not that I am no longer using a fork? Will reopen if it comes back.
